# Generated by Django 5.2.13 on 2026-04-29 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('close_value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('change_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'code'],
                'constraints': [models.UniqueConstraint(fields=('code', 'date'), name='unique_market_index_date')],
            },
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
                ('change_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='marketdata__stock_i_ffae78_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_daily_price')],
            },
        ),
        migrations.CreateModel(
            name='InvestorFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('foreign_net_buy', models.BigIntegerField(default=0)),
                ('institution_net_buy', models.BigIntegerField(default=0)),
                ('individual_net_buy', models.BigIntegerField(default=0)),
                ('program_net_buy', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_flows', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_investor_flow')],
            },
        ),
    ]
