# Generated by Django 5.2.13 on 2026-04-29 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDataCollectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('investor_flow', 'Investor Flow'), ('risk_event', 'Risk Event')], max_length=30)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('never', 'Never'), ('success', 'Success'), ('empty', 'Empty'), ('error', 'Error'), ('skipped', 'Skipped')], default='never', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_row_count', models.PositiveIntegerField(default=0)),
                ('last_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_statuses', to='stocks.stock')),
            ],
            options={
                'ordering': ['data_type', 'stock__code'],
                'indexes': [models.Index(fields=['data_type', 'status'], name='marketdata__data_ty_0cf3d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'data_type'), name='unique_stock_collection_status_type')],
            },
        ),
    ]
