# Generated by Django 5.2.13 on 2026-04-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_stockdatacollectionstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdatacollectionstatus',
            name='data_type',
            field=models.CharField(choices=[('investor_flow', 'Investor Flow'), ('risk_event', 'Risk Event'), ('financial_snapshot', 'Financial Snapshot')], max_length=30),
        ),
    ]
