# Generated by Django 5.2.13 on 2026-04-29 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('holdings', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('grade', models.CharField(choices=[('A', 'A - Reviewable'), ('B', 'B - Watch'), ('C', 'C - Avoid Averaging Down'), ('D', 'D - Review Stop Loss')], max_length=1)),
                ('decision', models.CharField(max_length=100)),
                ('reason_summary', models.TextField()),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('score_breakdown', models.JSONField(blank=True, default=dict)),
                ('suggested_budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('disclaimer', models.TextField(default='본 결과는 투자 참고용 데이터 분석이며, 매수·매도 추천이 아닙니다. 최종 투자 판단과 책임은 사용자 본인에게 있습니다.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='holdings.userholding')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['holding', '-created_at'], name='decisions_a_holding_1d71ce_idx'), models.Index(fields=['grade', '-created_at'], name='decisions_a_grade_13c87a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('trading_halt', 'Trading Halt'), ('delisting_risk', 'Delisting Risk'), ('managed_stock', 'Managed Stock'), ('audit_opinion_rejected', 'Audit Opinion Rejected'), ('capital_reduction', 'Capital Reduction'), ('paid_in_capital_increase', 'Paid-in Capital Increase'), ('embezzlement', 'Embezzlement'), ('earnings_shock', 'Earnings Shock'), ('operating_loss', 'Operating Loss'), ('capital_impairment', 'Capital Impairment'), ('disclosure_violation', 'Disclosure Violation'), ('other', 'Other')], max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True)),
                ('event_date', models.DateField(db_index=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='stocks.stock')),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['stock', '-event_date'], name='decisions_r_stock_i_fb417a_idx'), models.Index(fields=['risk_level', 'is_active'], name='decisions_r_risk_le_dfe2d0_idx')],
            },
        ),
    ]
