# Generated by Django 5.2.13 on 2026-04-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskevent',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='riskevent',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('source_key',), name='unique_risk_event_source_key'),
        ),
    ]
