# Generated by Django 5.2.13 on 2026-04-30 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0002_riskevent_source_key_and_more'),
        ('holdings', '0002_userholding_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AveragingProbabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_input', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('success_probability', models.DecimalField(decimal_places=4, max_digits=6)),
                ('failure_probability', models.DecimalField(decimal_places=4, max_digits=6)),
                ('neutral_probability', models.DecimalField(decimal_places=4, max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=6)),
                ('disclaimer', models.TextField(default='본 결과는 과거 데이터와 현재 조건 기반의 추정 확률이며, 매수·매도 추천이 아닙니다. 미래 수익 또는 손실 회피를 보장하지 않습니다.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probability_records', to='holdings.userholding')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['holding', '-created_at'], name='decisions_a_holding_64e4d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='HoldingConsultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_input', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('final_grade', models.CharField(choices=[('A', 'A - Reviewable'), ('B', 'B - Watch'), ('C', 'C - Avoid Averaging Down'), ('D', 'D - Review Stop Loss')], max_length=1)),
                ('consulting_status', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('disclaimer', models.TextField(default='본 결과는 투자 참고용 데이터 분석이며, 매수·매도 추천이 아닙니다. 미래 수익 또는 손실 회피를 보장하지 않습니다. 최종 투자 판단과 책임은 사용자 본인에게 있습니다.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consult_records', to='holdings.userholding')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['holding', '-created_at'], name='decisions_h_holding_b64295_idx'), models.Index(fields=['final_grade', '-created_at'], name='decisions_h_final_g_4ceb70_idx')],
            },
        ),
    ]
