# Generated by Django 5.2.13 on 2026-04-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0002_financialsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('target_type', models.CharField(choices=[('stock', 'Stock'), ('price', 'Price'), ('flow', 'Investor Flow'), ('market', 'Market'), ('risk', 'Risk Event'), ('financial', 'Financial'), ('quality', 'Data Quality')], max_length=30)),
                ('target_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='started', max_length=20)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['job_name', '-started_at'], name='data_pipeli_job_nam_c4fa92_idx'), models.Index(fields=['provider', '-started_at'], name='data_pipeli_provide_ea870b_idx'), models.Index(fields=['status', '-started_at'], name='data_pipeli_status_c4fc44_idx'), models.Index(fields=['target_type', 'target_code'], name='data_pipeli_target__c3f811_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataProviderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('data_type', models.CharField(choices=[('stock', 'Stock'), ('price', 'Price'), ('flow', 'Investor Flow'), ('market', 'Market'), ('risk', 'Risk Event'), ('financial', 'Financial'), ('quality', 'Data Quality')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('average_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'data_type'],
                'indexes': [models.Index(fields=['provider', 'data_type'], name='data_pipeli_provide_83d421_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'data_type'), name='unique_provider_data_type_status')],
            },
        ),
        migrations.CreateModel(
            name='DataQualitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField(db_index=True)),
                ('price_data_days', models.PositiveIntegerField(default=0)),
                ('latest_price_date', models.DateField(blank=True, null=True)),
                ('latest_price_age_days', models.PositiveIntegerField(blank=True, null=True)),
                ('investor_flow_days', models.PositiveIntegerField(default=0)),
                ('latest_flow_date', models.DateField(blank=True, null=True)),
                ('market_data_available', models.BooleanField(default=False)),
                ('risk_event_checked_at', models.DateTimeField(blank=True, null=True)),
                ('financial_data_available', models.BooleanField(default=False)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('overall_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('quality_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_snapshots', to='stocks.stock')),
            ],
            options={
                'ordering': ['stock__code', '-as_of_date'],
                'indexes': [models.Index(fields=['stock', '-as_of_date'], name='data_pipeli_stock_i_72698d_idx'), models.Index(fields=['quality_grade', '-as_of_date'], name='data_pipeli_quality_571f76_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'as_of_date'), name='unique_stock_data_quality_snapshot_date')],
            },
        ),
    ]
