# Generated by Django 5.2.14 on 2026-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataingestionlog',
            name='commit_mode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='dry_run',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='endpoint_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='error_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='http_status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='job_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='market',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='network_call',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='provider_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='safe_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='saved_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='target_symbol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='updated_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataingestionlog',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataingestionlog',
            name='target_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('price', 'Price'), ('flow', 'Investor Flow'), ('market', 'Market'), ('risk', 'Risk Event'), ('financial', 'Financial'), ('quality', 'Data Quality'), ('provider_health', 'Provider Health'), ('auth', 'Authentication'), ('quote', 'Quote'), ('smoke', 'Smoke'), ('daily_price', 'Daily Price')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dataproviderstatus',
            name='data_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('price', 'Price'), ('flow', 'Investor Flow'), ('market', 'Market'), ('risk', 'Risk Event'), ('financial', 'Financial'), ('quality', 'Data Quality'), ('provider_health', 'Provider Health'), ('auth', 'Authentication'), ('quote', 'Quote'), ('smoke', 'Smoke'), ('daily_price', 'Daily Price')], max_length=30),
        ),
    ]
