# Generated by Django 5.2.14 on 2026-06-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0002_dataingestionlog_commit_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataingestionlog',
            name='candidate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dataingestionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
