# Generated by Django 5.2.14 on 2026-06-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_pipeline', '0003_dataingestionlog_candidate_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataingestionlog',
            name='target_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('price', 'Price'), ('flow', 'Investor Flow'), ('market', 'Market'), ('risk', 'Risk Event'), ('financial', 'Financial'), ('quality', 'Data Quality'), ('provider_health', 'Provider Health'), ('auth', 'Authentication'), ('quote', 'Quote'), ('smoke', 'Smoke'), ('daily_price', 'Daily Price'), ('holdings', 'Holdings')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dataproviderstatus',
            name='data_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('price', 'Price'), ('flow', 'Investor Flow'), ('market', 'Market'), ('risk', 'Risk Event'), ('financial', 'Financial'), ('quality', 'Data Quality'), ('provider_health', 'Provider Health'), ('auth', 'Authentication'), ('quote', 'Quote'), ('smoke', 'Smoke'), ('daily_price', 'Daily Price'), ('holdings', 'Holdings')], max_length=30),
        ),
    ]
