# Generated by Django 5.2.13 on 2026-04-29 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ma5', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ma20', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ma60', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ma120', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rsi14', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('macd_signal', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('macd_histogram', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('atr14', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('volume_ma20', models.BigIntegerField(blank=True, null=True)),
                ('bb_upper', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bb_middle', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bb_lower', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_indicators', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='indicators__stock_i_6d308e_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='unique_stock_technical_indicator')],
            },
        ),
    ]
