# Merge this ingress block into /etc/cloudflared/config.yml
- hostname: stock.thesysm.com
  service: http://localhost
  originRequest:
    unixSocketPath: /run/gunicorn_thestock.sock
    httpHostHeader: stock.thesysm.com
