server {
    listen 80;
    server_name stock.thesysm.com;
    include proxy_params;
    include /etc/nginx/snippets/common_django_app.conf;

    location / {
        proxy_pass http://unix:/run/gunicorn_thestock.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/ {
        alias /var/www/thestock/static/;
        expires 30d;
    }

    location /media/ {
        alias /var/www/thestock/media/;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        log_not_found off;
        access_log off;
    }
}
