# Generated by Django 5.2.14 on 2026-06-17 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TossInvestCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='toss_invest', max_length=32)),
                ('client_id_ciphertext', models.TextField(blank=True, null=True)),
                ('client_secret_ciphertext', models.TextField(blank=True, null=True)),
                ('access_token_ciphertext', models.TextField(blank=True, null=True)),
                ('refresh_token_ciphertext', models.TextField(blank=True, null=True)),
                ('client_id_key_version', models.CharField(blank=True, default='', max_length=32)),
                ('client_secret_key_version', models.CharField(blank=True, default='', max_length=32)),
                ('access_token_key_version', models.CharField(blank=True, default='', max_length=32)),
                ('refresh_token_key_version', models.CharField(blank=True, default='', max_length=32)),
                ('client_id_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('account_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('account_masked', models.CharField(blank=True, default='', max_length=80)),
                ('external_user_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending verification'), ('active', 'Active'), ('disconnected', 'Disconnected'), ('revoked', 'Revoked'), ('reset_required', 'Reset required'), ('error', 'Error')], db_index=True, default='pending_verification', max_length=32)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=120)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toss_invest_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='toss_invest', max_length=32)),
                ('actor_ref_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('target_user_ref_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('action', models.CharField(choices=[('credential_create', 'Credential create'), ('credential_update', 'Credential update'), ('credential_reset', 'Credential reset'), ('credential_disconnect', 'Credential disconnect'), ('credential_reveal_attempt', 'Credential reveal attempt'), ('credential_reveal_success', 'Credential reveal success'), ('credential_reveal_failure', 'Credential reveal failure'), ('credential_verification_success', 'Credential verification success'), ('credential_verification_failure', 'Credential verification failure'), ('token_refresh', 'Token refresh'), ('holdings_sync', 'Holdings sync'), ('order_history_sync', 'Order history sync'), ('staff_masked_view', 'Staff masked view'), ('permission_denied', 'Permission denied'), ('decryption_failure', 'Decryption failure')], db_index=True, max_length=64)),
                ('account_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('reason_code', models.CharField(blank=True, default='', max_length=120)),
                ('error_code', models.CharField(blank=True, default='', max_length=120)),
                ('safe_summary', models.TextField(blank=True, default='')),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_audit_events', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_integration_audit_events', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='integrations.tossinvestcredential')),
            ],
        ),
        migrations.AddIndex(
            model_name='tossinvestcredential',
            index=models.Index(fields=['provider', 'status'], name='idx_int_cred_provider_status'),
        ),
        migrations.AddIndex(
            model_name='tossinvestcredential',
            index=models.Index(fields=['status', 'updated_at'], name='idx_int_cred_status_updated'),
        ),
        migrations.AddIndex(
            model_name='tossinvestcredential',
            index=models.Index(fields=['user', 'status'], name='idx_int_cred_user_status'),
        ),
        migrations.AddIndex(
            model_name='tossinvestcredential',
            index=models.Index(fields=['account_hash'], name='idx_int_cred_account_hash'),
        ),
        migrations.AddIndex(
            model_name='tossinvestcredential',
            index=models.Index(fields=['client_id_fingerprint'], name='idx_int_cred_client_fp'),
        ),
        migrations.AddConstraint(
            model_name='tossinvestcredential',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending_verification', 'active', 'disconnected', 'revoked', 'reset_required', 'error'])), name='ck_int_toss_cred_status'),
        ),
        migrations.AddConstraint(
            model_name='tossinvestcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id_fingerprint__isnull', False), ('status__in', ['pending_verification', 'active'])), fields=('provider', 'client_id_fingerprint'), name='uniq_int_active_pending_client_fp'),
        ),
        migrations.AddConstraint(
            model_name='tossinvestcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('account_hash__isnull', False), ('status', 'active')), fields=('provider', 'account_hash'), name='uniq_int_active_account_hash'),
        ),
        migrations.AddIndex(
            model_name='integrationauditlog',
            index=models.Index(fields=['provider', 'action', 'created_at'], name='idx_int_audit_provider_action'),
        ),
        migrations.AddIndex(
            model_name='integrationauditlog',
            index=models.Index(fields=['actor_ref_hash', 'created_at'], name='idx_int_audit_actor_hash'),
        ),
        migrations.AddIndex(
            model_name='integrationauditlog',
            index=models.Index(fields=['target_user_ref_hash', 'created_at'], name='idx_int_audit_target_hash'),
        ),
        migrations.AddIndex(
            model_name='integrationauditlog',
            index=models.Index(fields=['account_hash', 'created_at'], name='idx_int_audit_account_hash'),
        ),
        migrations.AddIndex(
            model_name='integrationauditlog',
            index=models.Index(fields=['success', 'created_at'], name='idx_int_audit_success'),
        ),
    ]
