# Generated by Django 5.2.14 on 2026-06-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tossinvestcredential',
            name='access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tossinvestcredential',
            name='access_token_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tossinvestcredential',
            name='access_token_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tossinvestcredential',
            name='account_ref_ciphertext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tossinvestcredential',
            name='account_ref_key_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
