# Generated by Django 5.2.14 on 2026-06-18 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_toss_account_ref_and_token_metadata'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TossTradeImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='toss_invest', max_length=32)),
                ('account_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('order_id_hash', models.CharField(db_index=True, max_length=64)),
                ('execution_digest', models.CharField(db_index=True, max_length=64)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('side', models.CharField(db_index=True, max_length=16)),
                ('source_status', models.CharField(blank=True, default='', max_length=48)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('ordered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('filled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('filled_quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('average_filled_price', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('filled_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('settlement_date', models.CharField(blank=True, default='', max_length=32)),
                ('import_result', models.CharField(db_index=True, max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_import_records', to='integrations.tossinvestcredential')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toss_import_records', to='portfolio.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toss_trade_import_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'filled_at'], name='idx_int_trade_import_user_fill'), models.Index(fields=['import_result', 'created_at'], name='idx_int_trade_import_result'), models.Index(fields=['symbol', 'filled_at'], name='idx_int_trade_import_symbol')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider', 'account_hash', 'order_id_hash'), name='uniq_int_toss_trade_order')],
            },
        ),
        migrations.CreateModel(
            name='TossTradeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, default='toss_invest', max_length=32)),
                ('initial_sync_completed', models.BooleanField(default=False)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_ordered_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_filled_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_mode', models.CharField(blank=True, default='', max_length=32)),
                ('last_run_status', models.CharField(db_index=True, default='never', max_length=32)),
                ('last_run_counts', models.JSONField(blank=True, default=dict)),
                ('last_error_code', models.CharField(blank=True, default='', max_length=120)),
                ('last_error_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sync_state', to='integrations.tossinvestcredential')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toss_trade_sync_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'last_run_status'], name='idx_int_trade_state_status'), models.Index(fields=['last_successful_sync_at'], name='idx_int_trade_state_success')],
            },
        ),
    ]
