# Generated by Django 5.2.13 on 2026-04-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holdings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userholding',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
