# Generated by Django 5.2.13 on 2026-04-29 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveIntegerField()),
                ('period_type', models.CharField(choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('ANNUAL', 'ANNUAL')], max_length=10)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('operating_cash_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('debt_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('capital_impairment_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('per', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pbr', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('source_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='stocks.stock')),
            ],
            options={
                'verbose_name': 'Financial Snapshot',
                'verbose_name_plural': 'Financial Snapshots',
                'ordering': ['stock_id', '-fiscal_year', '-reported_date', 'period_type'],
                'indexes': [models.Index(fields=['stock', '-reported_date'], name='stocks_fina_stock_i_9d68d0_idx'), models.Index(fields=['stock', '-fiscal_year', 'period_type'], name='stocks_fina_stock_i_a0c569_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'fiscal_year', 'period_type'), name='unique_stock_financial_snapshot_period')],
            },
        ),
    ]
